- name: Dave Troy
  available_rooms: 3
  description: "Yo, I've got this house, it's in Bolton Hill, I just bought it.  Rock."
  lat: 39.308601
  lon: -76.627064
  email: 'davetroy@gmail.com'
- name: Nick Evans
  available_rooms: 1
  description: "It might look like he's got long hair, but you apparently haven't seen the rest of the Baltimore crew.  In any case, Nick is another fine gentleman and would be a catch for any would-be room crasher."
  lat: 39.36443
  lon: -76.609383
  email: nick@ekenosen.net
- name: David Robson
  available_rooms: 2
  email: david@edplans.com
- name: Yair Flicker
  available_rooms: 1
  description: "I'll throw in a home-cooked meal."
  lat: 39.344653
  lon: -76.629896
  email: yair@smartlogicsolutions.com
- name: Paul Barry
  available_rooms: 1
  description: "Actually, the baby doesn't cry very loudly at night. Anymore."
  lat: 39.27381
  lon: -76.610112
  email: pauljbarry3@gmail.com
- name: Sinclair Bain
  available_rooms: 1
  description: "Let's meet for a pint."
  lat: 39.361511
  lon: -76.64938
  email: sinclair.bain@gmail.com
- name: Jonathan Julian
  available_rooms: 1
  description: "My room is 100 feet closer to the convention center than Paul's."
  lat: 39.274399
  lon: -76.610252
  email: jonathan.m.julian@gmail.com
- name: Matt Scilipoti
  available_rooms: 1
  description: "Hey, this guy is one interesting dude.  He's a talkative guy and one heckuva coder!  Plus he's got a room for you to stay in."
  lat: 39.207916
  lon: -76.837006
  email: matts@possiamo.com
- name: Vinny
  available_rooms: 1
  email: agnellvj@gmail.com