- name: Dave Troy
  available_rooms: 3
  description: "Yo, I've got this house, it's in Bolton Hill, I just bought it.  Rock."
  lat: 39.308601
  lon: -76.627064
  email: 'davetroy@gmail.com'
  twitter: davetroy
- name: Nick Evans
  available_rooms: 1
  description: "It might look like he's got long hair, but you apparently haven't seen the rest of the Baltimore crew.  In any case, Nick is another fine gentleman and would be a catch for any would-be room crasher."
  lat: 39.36443
  lon: -76.609383
  email: nick@ekenosen.net
  twitter: nick_evans
- name: David Robson
  available_rooms: 2
  description: "Dave is a retired H.S. Physics teacher and an amateur coder who is now P.D. on a RoR project developing apps for school teachers. Will try to provide transportation to/from the RailsConf site; private room!"
  lat: 39.41312
  lon: -76.653006
  email: david@edplans.com
  twitter:
- name: Yair Flicker
  available_rooms: 1
  description: "I live in Evergreen.  Come stay with me and I'll buy you a bagel.  I have a shih tzu."
  lat: 39.344653
  lon: -76.629896
  email: yair@smartlogicsolutions.com
  twitter: yflicker
- name: Paul Barry
  available_rooms: 1
  description: "Paul's house is in Federal Hill, a neighborhood within walking distance to the Conference Center, but beware, he's a fan of both Functional Programming and the Yankees."
  lat: 39.27381
  lon: -76.610112
  email: pauljbarry3@gmail.com
  twitter: pjb3
- name: Sinclair Bain
  available_rooms: 1
  description: "Enjoys Ruby, Rails and occasional ales, the odd glass of whisky and some Smalltalk. Been in Baltimore ever since leaving 'the old country' 15 years ago."
  lat: 39.37163
  lon: -76.64938
  email: sinclair.bain@gmail.com
  twitter: sinclairbain
- name: Jonathan Julian
  available_rooms: 1
  description: "I'm an independent web developer who loves Ruby, the Rails framework, and general geekiness. My house in Federal Hill is a pleasant 15-minute walk from the convention center."
  lat: 39.274399
  lon: -76.610252
  email: jonathan.m.julian@gmail.com
  twitter: jonathanjulian
- name: Matt Scilipoti
  available_rooms: 1
  description: "Hey, this guy is one interesting dude.  He's a talkative guy and one heckuva coder!  Plus he's got a room for you to stay in."
  lat: 39.207916
  lon: -76.837006
  email: matts@possiamo.com
  twitter: mattscilipoti
- name: Vincent Agnello
  available_rooms: 1
  description: "This slick fun-loving guy will take you out for a Scotch."
  lat: 39.286433
  lon: -76.598032
  email: agnellvj@gmail.com
  twitter: agnellvj
