- name: Dave Troy
  available_rooms: 3
  description: "Yo, I've got this house, it's in Bolton Hill, I just bought it.  Rock."
- name: Nick Evans
  available_rooms: 1
  description: "It might look like he's got long hair, but you apparently haven't seen the rest of the Baltimore crew.  In any case, Nick is another fine gentleman and would be a catch for any would-be room crasher."
- name: David Robson
  available_rooms: 2
- name: Yair Flicker
  available_rooms: 1
- name: Paul Barry
  available_rooms: 1
- name: Sinclair Bain
  available_rooms: 1
- name: Jonathan Julian
  available_rooms: 1
  lat: 39.300089
  lon: -76.6095
- name: Matt Scilipoti
  available_rooms: 1
  description: "Hey, this guy is one interesting dude.  He's a talkative guy and one heckuva coder!  Plus he's got a room for you to stay in."