- name: Dave Troy
  available_rooms: 3
- name: Nick Evans
  available_rooms: 1
- name: David Robson
  available_rooms: 2
- name: Yair Flicker
  available_rooms: 1
- name: Paul Barry
  available_rooms: 1
- name: Sinclair Bain
  available_rooms: 1
- name: Jonathan Julian
  available_rooms: 1
- name: Matt Scilipoti
  available_rooms: 1