- name: Dave Troy
  rooms: 3
- name: Nick Evans
  rooms: 1
- name: David Robson
  rooms: 2
- name: Yair Flicker
  rooms: 1
- name: Paul Barry
  rooms: 1
- name: Sinclair Bain
  rooms: 1
- name: Jonathan Julian
  rooms: 1
- name: Matt Scilipoti
  rooms: 1
